name: Keep Render Alive

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -s https://pitlaneinsiders-backend.onrender.com/ > /dev/null
